name: R CI/CD
on:
  push:
    branches: "main"
  pull_request:
    branches: "main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        r-version: ['3.6.3', '4.1.1', '4.3.1', '4.3.2']
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          R -e 'install.packages(c("tidyverse", "tidyr", "usethis", "viridis","ggplot2","dplyr", "httr",
                             "jsonlite", "stringr", "lubridate", "ggrepel", "ggtext", "gridExtra",
                             "viridis","anytime","kableExtra"))'
          R -e 'install.packages(c("remotes", "rcmdcheck")); remotes::install_deps(dependencies = TRUE)'
      - name: Run Tests
        run: Rscript -e 'testthat::test_dir("tests/testthat")'
      - name: Check Package
        run: R CMD check
